-- Seed 2026 F1 Calendar
-- Future meetings inserted with NULL openf1_meeting_key (will be filled when data is ingested)
-- 
-- meeting_id format: mtg:{season}-{Meeting-Name-With-Dashes}
--   This matches the format generated by upsert_meetings.py:generate_meeting_id()
--   e.g., mtg:2026-Australian-Grand-Prix
--
-- NOTE: The seed CSV (meetings_export.csv) uses a DIFFERENT format (mtg:{name}-{year}, lowercase)
--       This inconsistency means existing seed data may not match upsert-generated IDs.
--       Consider standardizing the format across the codebase.

-- First, create the new Madrid circuit (new for 2026)
-- NOTE: openf1_circuit_key is TBD - using placeholder until OpenF1 assigns one
INSERT INTO silver.circuits (
    circuit_id,
    openf1_circuit_key,
    circuit_short_name,
    country_code,
    location,
    lat,
    lon,
    circuit_name
) VALUES (
    'circuit:Madrid-tbd',
    'tbd',  -- Will be updated when OpenF1 assigns a key
    'Madrid',
    'ESP',
    'Madrid',
    40.453054,  -- Approximate coordinates for the new Madrid circuit
    -3.688344,
    'Madrid Street Circuit'
) ON CONFLICT (circuit_id) DO NOTHING;

-- Insert 2026 meetings
-- Round numbers exclude pre-season testing
-- date_start is the Friday FP1 start time in UTC (approximated based on typical session times)
-- meeting_id format matches upsert_meetings.py: mtg:{season}-{sanitized_name}

INSERT INTO silver.meetings (meeting_id, circuit_id, meeting_name, season, date_start, round_number, openf1_meeting_key)
VALUES
    -- Round 1: Australian Grand Prix - March 6-8, 2026
    ('mtg:2026-Australian-Grand-Prix', 'circuit:Melbourne-10', 'Australian Grand Prix', 2026, '2026-03-06 01:30:00+00', 1, NULL),
    
    -- Round 2: Chinese Grand Prix - March 13-15, 2026
    ('mtg:2026-Chinese-Grand-Prix', 'circuit:Shanghai-49', 'Chinese Grand Prix', 2026, '2026-03-13 03:30:00+00', 2, NULL),
    
    -- Round 3: Japanese Grand Prix - March 27-29, 2026
    ('mtg:2026-Japanese-Grand-Prix', 'circuit:Suzuka-46', 'Japanese Grand Prix', 2026, '2026-03-27 02:30:00+00', 3, NULL),
    
    -- Round 4: Bahrain Grand Prix - April 10-12, 2026
    ('mtg:2026-Bahrain-Grand-Prix', 'circuit:Sakhir-63', 'Bahrain Grand Prix', 2026, '2026-04-10 11:30:00+00', 4, NULL),
    
    -- Round 5: Saudi Arabian Grand Prix - April 17-19, 2026
    ('mtg:2026-Saudi-Arabian-Grand-Prix', 'circuit:Jeddah-149', 'Saudi Arabian Grand Prix', 2026, '2026-04-17 13:30:00+00', 5, NULL),
    
    -- Round 6: Miami Grand Prix - May 1-3, 2026
    ('mtg:2026-Miami-Grand-Prix', 'circuit:Miami-151', 'Miami Grand Prix', 2026, '2026-05-01 16:30:00+00', 6, NULL),
    
    -- Round 7: Canadian Grand Prix - May 22-24, 2026
    ('mtg:2026-Canadian-Grand-Prix', 'circuit:Montreal-23', 'Canadian Grand Prix', 2026, '2026-05-22 17:30:00+00', 7, NULL),
    
    -- Round 8: Monaco Grand Prix - June 5-7, 2026
    ('mtg:2026-Monaco-Grand-Prix', 'circuit:Monte Carlo-22', 'Monaco Grand Prix', 2026, '2026-06-05 11:30:00+00', 8, NULL),
    
    -- Round 9: Spanish Grand Prix - June 12-14, 2026 (Barcelona)
    ('mtg:2026-Spanish-Grand-Prix', 'circuit:Catalunya-15', 'Spanish Grand Prix', 2026, '2026-06-12 11:30:00+00', 9, NULL),
    
    -- Round 10: Austrian Grand Prix - June 26-28, 2026
    ('mtg:2026-Austrian-Grand-Prix', 'circuit:Spielberg-19', 'Austrian Grand Prix', 2026, '2026-06-26 10:30:00+00', 10, NULL),
    
    -- Round 11: British Grand Prix - July 3-5, 2026
    ('mtg:2026-British-Grand-Prix', 'circuit:Silverstone-2', 'British Grand Prix', 2026, '2026-07-03 11:30:00+00', 11, NULL),
    
    -- Round 12: Belgian Grand Prix - July 17-19, 2026
    ('mtg:2026-Belgian-Grand-Prix', 'circuit:Spa-Francorchamps-7', 'Belgian Grand Prix', 2026, '2026-07-17 10:30:00+00', 12, NULL),
    
    -- Round 13: Hungarian Grand Prix - July 24-26, 2026
    ('mtg:2026-Hungarian-Grand-Prix', 'circuit:Hungaroring-4', 'Hungarian Grand Prix', 2026, '2026-07-24 11:30:00+00', 13, NULL),
    
    -- Round 14: Dutch Grand Prix - August 21-23, 2026
    ('mtg:2026-Dutch-Grand-Prix', 'circuit:Zandvoort-55', 'Dutch Grand Prix', 2026, '2026-08-21 10:30:00+00', 14, NULL),
    
    -- Round 15: Italian Grand Prix - September 4-6, 2026
    ('mtg:2026-Italian-Grand-Prix', 'circuit:Monza-39', 'Italian Grand Prix', 2026, '2026-09-04 11:30:00+00', 15, NULL),
    
    -- Round 16: Madrid Grand Prix - September 11-13, 2026 (NEW CIRCUIT)
    ('mtg:2026-Madrid-Grand-Prix', 'circuit:Madrid-tbd', 'Madrid Grand Prix', 2026, '2026-09-11 11:30:00+00', 16, NULL),
    
    -- Round 17: Azerbaijan Grand Prix - September 24-26, 2026
    ('mtg:2026-Azerbaijan-Grand-Prix', 'circuit:Baku-144', 'Azerbaijan Grand Prix', 2026, '2026-09-24 09:30:00+00', 17, NULL),
    
    -- Round 18: Singapore Grand Prix - October 9-11, 2026
    ('mtg:2026-Singapore-Grand-Prix', 'circuit:Singapore-61', 'Singapore Grand Prix', 2026, '2026-10-09 09:30:00+00', 18, NULL),
    
    -- Round 19: United States Grand Prix - October 23-25, 2026
    ('mtg:2026-United-States-Grand-Prix', 'circuit:Austin-9', 'United States Grand Prix', 2026, '2026-10-23 17:30:00+00', 19, NULL),
    
    -- Round 20: Mexico City Grand Prix - October 30 - November 1, 2026
    ('mtg:2026-Mexico-City-Grand-Prix', 'circuit:Mexico City-65', 'Mexico City Grand Prix', 2026, '2026-10-30 18:30:00+00', 20, NULL),
    
    -- Round 21: São Paulo Grand Prix - November 6-8, 2026
    -- Note: São becomes "So" after sanitization (non-ASCII chars stripped by isalnum())
    ('mtg:2026-So-Paulo-Grand-Prix', 'circuit:Interlagos-14', 'São Paulo Grand Prix', 2026, '2026-11-06 14:30:00+00', 21, NULL),
    
    -- Round 22: Las Vegas Grand Prix - November 19-21, 2026
    ('mtg:2026-Las-Vegas-Grand-Prix', 'circuit:Las Vegas-152', 'Las Vegas Grand Prix', 2026, '2026-11-19 02:30:00+00', 22, NULL),
    
    -- Round 23: Qatar Grand Prix - November 27-29, 2026
    ('mtg:2026-Qatar-Grand-Prix', 'circuit:Lusail-150', 'Qatar Grand Prix', 2026, '2026-11-27 13:30:00+00', 23, NULL),
    
    -- Round 24: Abu Dhabi Grand Prix - December 4-6, 2026
    ('mtg:2026-Abu-Dhabi-Grand-Prix', 'circuit:Yas Marina Circuit-70', 'Abu Dhabi Grand Prix', 2026, '2026-12-04 09:30:00+00', 24, NULL)

ON CONFLICT (meeting_id) DO UPDATE SET
    circuit_id = EXCLUDED.circuit_id,
    meeting_name = EXCLUDED.meeting_name,
    season = EXCLUDED.season,
    date_start = EXCLUDED.date_start,
    round_number = EXCLUDED.round_number;

-- Summary:
-- 24 races for 2026 season
-- NEW: Madrid Grand Prix (Round 16) - requires new circuit entry (created above)
-- NOTE: São Paulo Grand Prix maintains existing naming (not "Brazilian Grand Prix")
-- NOTE: Both Spanish GP (Barcelona) and Madrid GP are on the calendar
-- All openf1_meeting_key values are NULL - will be filled when OpenF1 data is ingested
--
-- IMPORTANT FORMAT NOTE:
-- This file uses the format from upsert_meetings.py: mtg:{season}-{Name}
-- The existing seed CSV uses a different format: mtg:{name-lowercase}-{year}
-- You may want to standardize this across the codebase to ensure proper matching.
